package model;

import java.io.Serializable;

/**
 * Data definition.
 * 
 * This file was generated by Ignite Web Console (07/18/2018, 15:31)
 **/
public class Data implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for avgW. */
    private Double avgW;

    /** Value for avgV. */
    private Double avgV;

    /** Value for sensor_id. */
    private String sensor_id;

    /** Value for granularity. */
    private String granularity;

    /** Value for TS. */
    private Double TS;

    /** Value for temperature. */
    private Double temperature;

    /** Value for appliances. */
    private String appliances;

    /** Value for action. */
    private String action;

    /** Value for user. */
    private String user;

    /** Empty constructor. **/
    public Data() {
        // No-op.
    }

    /** Full constructor. **/
    public Data(Double avgW,
        Double avgV,
        String sensor_id,
        String granularity,
        Double TS,
        Double temperature,
        String appliances,
        String action,
        String user) {
        this.avgW = avgW;
        this.avgV = avgV;
        this.sensor_id = sensor_id;
        this.granularity = granularity;
        this.TS = TS;
        this.temperature = temperature;
        this.appliances = appliances;
        this.action = action;
        this.user = user;
    }

    /**
     * Gets avgW
     * 
     * @return Value for avgW.
     **/
    public Double getAvgW() {
        return avgW;
    }

    /**
     * Sets avgW
     * 
     * @param avgW New value for avgW.
     **/
    public void setAvgW(Double avgW) {
        this.avgW = avgW;
    }

    /**
     * Gets avgV
     * 
     * @return Value for avgV.
     **/
    public Double getAvgV() {
        return avgV;
    }

    /**
     * Sets avgV
     * 
     * @param avgV New value for avgV.
     **/
    public void setAvgV(Double avgV) {
        this.avgV = avgV;
    }

    /**
     * Gets sensor_id
     * 
     * @return Value for sensor_id.
     **/
    public String getSensor_id() {
        return sensor_id;
    }

    /**
     * Sets sensor_id
     * 
     * @param sensor_id New value for sensor_id.
     **/
    public void setSensor_id(String sensor_id) {
        this.sensor_id = sensor_id;
    }

    /**
     * Gets granularity
     * 
     * @return Value for granularity.
     **/
    public String getGranularity() {
        return granularity;
    }

    /**
     * Sets granularity
     * 
     * @param granularity New value for granularity.
     **/
    public void setGranularity(String granularity) {
        this.granularity = granularity;
    }

    /**
     * Gets TS
     * 
     * @return Value for TS.
     **/
    public Double getTS() {
        return TS;
    }

    /**
     * Sets TS
     * 
     * @param TS New value for TS.
     **/
    public void setTS(Double TS) {
        this.TS = TS;
    }

    /**
     * Gets temperature
     * 
     * @return Value for temperature.
     **/
    public Double getTemperature() {
        return temperature;
    }

    /**
     * Sets temperature
     * 
     * @param temperature New value for temperature.
     **/
    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    /**
     * Gets appliances
     * 
     * @return Value for appliances.
     **/
    public String getAppliances() {
        return appliances;
    }

    /**
     * Sets appliances
     * 
     * @param appliances New value for appliances.
     **/
    public void setAppliances(String appliances) {
        this.appliances = appliances;
    }

    /**
     * Gets action
     * 
     * @return Value for action.
     **/
    public String getAction() {
        return action;
    }

    /**
     * Sets action
     * 
     * @param action New value for action.
     **/
    public void setAction(String action) {
        this.action = action;
    }

    /**
     * Gets user
     * 
     * @return Value for user.
     **/
    public String getUser() {
        return user;
    }

    /**
     * Sets user
     * 
     * @param user New value for user.
     **/
    public void setUser(String user) {
        this.user = user;
    }

    /** {@inheritDoc} **/
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        
        if (!(o instanceof Data))
            return false;
        
        Data that = (Data)o;

        if (avgW != null ? !avgW.equals(that.avgW) : that.avgW != null)
            return false;
        

        if (avgV != null ? !avgV.equals(that.avgV) : that.avgV != null)
            return false;
        

        if (sensor_id != null ? !sensor_id.equals(that.sensor_id) : that.sensor_id != null)
            return false;
        

        if (granularity != null ? !granularity.equals(that.granularity) : that.granularity != null)
            return false;
        

        if (TS != null ? !TS.equals(that.TS) : that.TS != null)
            return false;
        

        if (temperature != null ? !temperature.equals(that.temperature) : that.temperature != null)
            return false;
        

        if (appliances != null ? !appliances.equals(that.appliances) : that.appliances != null)
            return false;
        

        if (action != null ? !action.equals(that.action) : that.action != null)
            return false;
        

        if (user != null ? !user.equals(that.user) : that.user != null)
            return false;
        
        return true;
    }

    /** {@inheritDoc} **/
    @Override public int hashCode() {
        int res = avgW != null ? avgW.hashCode() : 0;

        res = 31 * res + (avgV != null ? avgV.hashCode() : 0);

        res = 31 * res + (sensor_id != null ? sensor_id.hashCode() : 0);

        res = 31 * res + (granularity != null ? granularity.hashCode() : 0);

        res = 31 * res + (TS != null ? TS.hashCode() : 0);

        res = 31 * res + (temperature != null ? temperature.hashCode() : 0);

        res = 31 * res + (appliances != null ? appliances.hashCode() : 0);

        res = 31 * res + (action != null ? action.hashCode() : 0);

        res = 31 * res + (user != null ? user.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} **/
    @Override public String toString() {
        return "Data [" + 
            "avgW=" + avgW + ", " + 
            "avgV=" + avgV + ", " + 
            "sensor_id=" + sensor_id + ", " + 
            "granularity=" + granularity + ", " + 
            "TS=" + TS + ", " + 
            "temperature=" + temperature + ", " + 
            "appliances=" + appliances + ", " + 
            "action=" + action + ", " + 
            "user=" + user +
        "]";
    }
}