package startup;

import model.BitmapHour;
import model.BitmapMinute;
import org.apache.ignite.Ignite;
import org.apache.ignite.IgniteCache;
import org.apache.ignite.Ignition;
import org.apache.ignite.cache.CacheAtomicityMode;
import org.apache.ignite.cache.CacheMode;
import org.apache.ignite.cache.query.FieldsQueryCursor;
import org.apache.ignite.cache.query.SqlFieldsQuery;
import org.apache.ignite.configuration.CacheConfiguration;
import org.apache.ignite.configuration.DataStorageConfiguration;
import org.apache.ignite.configuration.IgniteConfiguration;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;

import java.util.List;

/** This file was generated by Ignite Web Console (07/01/2018, 15:17) **/
public class InitCache {
    /**
     * Start up node with specified configuration.
     *
     * @param args Command line arguments, none required.
     * @throws Exception If failed.
     **/
    public static void main(String[] args) throws Exception {


        Logger.getLogger("org").setLevel(Level.OFF);
        Logger.getLogger("akka").setLevel(Level.OFF);

        System.setProperty("IGNITE_QUIET", "false");

        IgniteConfiguration cfg = new IgniteConfiguration();

// Ignite persistence configuration.
        DataStorageConfiguration storageCfg = new DataStorageConfiguration();

// Enabling the persistence.
        storageCfg.getDefaultDataRegionConfiguration().setPersistenceEnabled(true);

// Applying settings.
        cfg.setDataStorageConfiguration(storageCfg);
        cfg.setClientMode(true);
        Ignite ignite= Ignition.start("BitmapCluster-client.xml");


        //   Ignite ignite=Ignition.start("BitmapCluster-client.xml");


        CacheConfiguration cfgc = new CacheConfiguration("CACHE1");
        cfgc.setCacheMode(CacheMode.PARTITIONED);
        cfgc.setAtomicityMode(CacheAtomicityMode.TRANSACTIONAL);

//        cfgc.setSqlSchema("CACHE");

        IgniteCache<Long, BitmapHour> bitmaphour = ignite.getOrCreateCache("BitmapHourCache");
//        bitmaphour.query(new SqlFieldsQuery("CREATE OR REPLACE TABLE BITMAP " +
//                "(id int primary key, avgW blob, avgV blob, sensor_id varchar)").setSchema("PUBLIC"));



        BitmapHour bm= new BitmapHour();
//        Blob b;
//        byte[] bt1= new byte[]{(byte)0xe0,(byte)0xe0};
        String bt="",bt1="";
        for(int i=0;i<65535;i++)
        {

            bt+="0";

        }
        String appstr="";


        for(int i=0;i<65535;i++)
        {

            bt1+="0";

        }
        bm.setAvgV(bt1);
        bm.setAvgW(bt);


        bm.setSensor_id("power_k_seil_a");

//        System.out.println(ignite.cacheNames());

//        bitmaphour.put(123L,bm);
//        Data v=bitmaphour.get(123L);




        System.out.println(bm.getAvgV());

        Expt.InsertIntoBitmapHour(bitmaphour,bm);



//****************************************************************************************************


        IgniteCache<Long, BitmapMinute> bitmapminute = ignite.getOrCreateCache("BitmapMinuteCache");
//        bitmaphour.query(new SqlFieldsQuery("CREATE OR REPLACE TABLE BITMAP " +
//                "(id int primary key, avgW blob, avgV blob, sensor_id varchar)").setSchema("PUBLIC"));



        BitmapMinute bmin= new BitmapMinute();
//        Blob b;
//        byte[] bt1= new byte[]{(byte)0xe0,(byte)0xe0};
        bt="";bt1="";
        for(int i=0;i<65535;i++)
        {

            bt+="0";

        }
        appstr="";


        for(int i=0;i<65535;i++)
        {

            bt1+="0";

        }
        bmin.setAvgV(bt1);
        bmin.setAvgW(bt);

        bmin.setAction(bt);
        bmin.setTemperature(bt);
        bmin.setAppliances(bt);
        bmin.setUser(bt);

        bmin.setSensor_id("power_k_seil_a");





        System.out.println(bmin.getAvgV());

        Expt.InsertIntoBitmapMinute(bitmapminute,bmin);




        FieldsQueryCursor<List<?>> cursor = bitmaphour.query(
                new SqlFieldsQuery("select * from BitmapHour"));


        String qwe="";
        //  Iterator<List<?>> iterator = cursor.iterator();
        for(List<?> r:cursor)
        {
            qwe = (String)r.get(0);
            System.out.println(qwe);
        }
        System.out.println("PRINTED CURSOR "+ qwe);


//        Collection<List<?>> cursor1 =
//                bitmaphour.query(
//                        new SqlFieldsQuery("select * from Data")).getAll();
//
//        System.out.println("HER   "+ cursor1);
//        for (List<?> row : cursor1) {
//            System.out.println("HER  "+row.get(0));
//        }
/*
        Data bm= new Data();
        Blob b;
        byte[] bt1= new byte[]{(byte)0xe0,(byte)0xe0};
        Double bt=123.0;
        bm.setAvgV(bt);
        bm.setAvgW(bt);
        bm.setGranularity("minute123131");
        bm.setTS(145.89745);
        bm.setSensor_id("power_k_seil_a");

//        System.out.println(ignite.cacheNames());

//        bitmaphour.put(123L,bm);
//        Data v=bitmaphour.get(123L);



//        Expt.InsertIntoData(bitmaphour,bm);
        bitmaphour.query(
                new SqlFieldsQuery("insert into Data (avgW,avgV,sensor_id,granularity,id,TS) values(112.0,134.0,'power_k_seil_l','hour',128,143.1241)"));
        QueryCursor<List<?>> cursor=
                bitmaphour.query(
                        new SqlFieldsQuery("select * from Data"));

        System.out.println("PRINTED CURSOR "+ cursor.getAll());

*/
//        bitmaphour.destroy();


    }
}